title: Rishi's Data Sciene Portfolio
description: Thanks for stopping by my data science portfolio!<br /> <br /> Feel free to contact me via email! <br /> rishig8803@gmail.com  
#logo: /assets/img/headshot_circle.png #description: text below image 
theme: jekyll-theme-minimal
